
const data = [
  {
    id: 1,
    title: "Buzoqbosh qo‘ng‘izlari ",
    description: "Melolonthinae",
    image: require("./assets/Melolonthinae.jpg"),
    image2: require("./assets/Id1_1.jpg"),
  },
  {
    id: 2,
    title: "Quyruqli buzoqbosh",
    description: "Gryllotolpa unispina Sauss",
    image: require("./assets/GryllotolpaunispinaSauss.jpg"),
    image2: require("./assets/Id2.jpg"),
  },
 
  {
    id: 3,
    title: "Kuzgi tunlam",
    description: "Agrotis segetum Siff.",
    image: require("./assets/AgrotissegetumSiff.jpg"),
    image2: require("./assets/Id3.jpg"),
  },
  {
    id: 4,
    title: "Simqurtlar",
    description: "Elateridae",
    image: require("./assets/Elateridae.jpg"),
    image2: require("./assets/Id4.jpg"),
  },
  {
    id: 5,
    title: "Archa unsimon qurti",
    description: "Planococcus vovae Nass.",
    image: require("./assets/Planococcus_vovae_Nass.jpg"),
    image2: require("./assets/Id5.jpg"),
  },
  {
    id: 6,
    title: "Virgin archa shirasi",
    description: "Juniperus schizaphis Graminum",
    image: require("./assets/Juniperus_schizaphi_Graminum.jpg"),
    image2: require("./assets/Id6.gif"),
  },
  {
    id: 7,
    title: "Katta shaftoli tana shirasi",
    description: "Pterochloroides persicae Chol.",
    image: require("./assets/Pterochloroides_persicae_Chol.jpg"),
    image2: require("./assets/Id7.jpg"),
  },
  {
    id: 8,
    title: "Qarag‘ay shirasi",
    description: "Сinara pini L.",
    image: require("./assets/Сinara_pini_L.jpg"),
    image2: require("./assets/Id8.jpg"),
  },
  {
    id: 9,
    title: "Qarag‘ay xermesi",
    description: "Pineus strobi",
    image: require("./assets/Pineus_strobi.jpg"),
    image2: require("./assets/Id9.jpg"),
  },
  {
    id: 10,
    title: "Kaliforniya qalqondori",
    description: "Diaspidiotus Perniciosus Comst.",
    image: require("./assets/Diaspidiotus_Perniciosus_Comst.jpg"),
  },
  {
    id: 11,
    title: "Vergulsimon qalqondor",
    description: "Lepidosaphes ulmi L.",
    image: require("./assets/Lepidosaphes_ulmi_L.jpg"),
    image2: require("./assets/Id11.jpg"),
  },
  {
    id: 12,
    title: "G‘arb tuyasi qalqondori",
    description: "Parthenolecanium fletcheri Cock.",
    image: require("./assets/Parthenolecanium_fletcheri_Cock.jpg"),
    image2: require("./assets/Id12.jpg"),
  },
  {
    id: 13,
    title: "Komstok qurti",
    description: "Pseudococcus comstocki Kuw.",
    image: require("./assets/Pseudococcus_comstocki_Kuw.jpg"),
    image2: require("./assets/Id13.jpg"),
  },
  {
    id: 14,
    title: "Qarag‘ay tunlami",
    description: "Panolis Jlammed Schij. J.",
    image: require("./assets/Panolis_Jlammed_Schij_J.jpg"),
  },
  {
  id: 15,
  title: "Toq ipak qurti",
  description: "Ocneria dispar L.",
  image: require("./assets/Ocneria_dispar_L.png"),
  },
  {
  id: 16,
  title: "Amerika oq kapalagi",
  description: "Iivphantria sipea Drury.",
  image: require("./assets/Iivphantria_sipea_Drury.jpg"),
  },
  {
  id: 17,
  title: "Shahar mo‘ylovdori",
  description: "Aeolesthes sarta Solsk.",
  image: require("./assets/Aeolesthes_sarta_Solsky.jpg"),
  },
  {
  id: 18,
  title: "Yog‘ochxo‘r kapalak",
  description: "Zeuzera pyrina L.",
  image: require("./assets/Zeuzera_pyrina_L.jpg"),
  },
  {
  id: 19,
  title: "Katta shoxdumli mo‘ylovdor",
  description: "Sirex gigas Tiuganus.",
  image: require("./assets/Sirex_gigas_Tiuganus.jpg"),
  },
  {
  id: 20,
  title: "Tyan-shan shox mo‘ylovdori",
  description: "Paururus juvencus, Paururus tianshanicus Sem.",
  image: require("./assets/Paururus_juvencus.jpg"),
  },
  {
  id: 21,
  title: "Po‘stloq osti qo‘ng‘izlari",
  description: "Scolytus rugulosus Ipidae.",
  image: require("./assets/Scolytus_rugulosus_Ipidae.jpg"),
  },
  {
  id: 22,
  title: "Qayrag‘och katta po‘stloqxo‘ri",
  description: "Scolytus scolytus Fabr.",
  image: require("./assets/Scolytus_scolytus_Fabr.jpg"),
  },
  {
  id: 23,
  title: "Burishgan po‘stloqxo‘r",
  description: "Scolytus rugulosus Rotz.",
  image: require("./assets/Scolytus_rugulosus_Rotz.jpg"),
  },
  {
    id: 24,
    title: "Archa tilla qo‘ng‘izi",
    description: "Anthaxia conradti Sem.",
    image: require("./assets/Anthaxia_conradti_Sem.jpg"),
    },
    {
    id: 25,
    title: "Archa urug‘xo‘ri",
    description: "Megastigmus iuniperi Nik.",
    image: require("./assets/Megastigmus_iuniperi_Nik.jpg"),
    },
    {
    id: 26,
    title: "Archa meva pashshasi",
    description: "Rhagoletis turaaica Rhod.",
    image: require("./assets/Rhagoletis_turaaica_Rhod.jpg"),
    },
    {
    id: 27,
    title: "Oddiy virgin archalarining zang kasalligi",
    description: "Gymnosporangium confusum",
    image: require("./assets/Gymnosporangium_confusum.jpg"),
    image2: require("./assets/Id27.jpg"),
  },
    {
    id: 28,
    title: "Un shudring kasalligi",
    description: "",
    image: require("./assets/Un_shudring_kasalligi.jpg"),
    },
    {
    id: 29,
    title: "Qarag‘ay daraxtlarining shyutte kasalligi",
    description: "Lophodermium pinastri",
    image: require("./assets/Lophodermium_pinus.jpg"),
    image2: require("./assets/Id29.jpg"),
  },
    {
    id: 30,
    title: "Igna bargli daraxtlarning sitosporoz kasalligi",
    description: "",
    image: require("./assets/Igna_bargli_daraxtlarning_sitosporoz_kasalligi.jpg"),
    image2: require("./assets/Id30.jpg"),
  },
    {
    id: 31,
    title: "Igna barglilar va butalarning bo‘qoq kasalligi",
    description: "Daldinia concentrica",
    image: require("./assets/Igna_barglilar_va_butalarning_bo‘qoq_kasalligi.jpg"),
    },
    {
    id: 32,
    title: "Igna bargli daraxtlar ildiz bo‘g‘zining rak kasalligi",
    description: "",
    image: require("./assets/Igna_bargli_daraxtlar_ildiz_bo‘g‘zining_rak_kasalligi.png"),
    image2: require("./assets/Id32.jpg"),
  },
    {
    id: 33,
    title: "Qarag‘ayning vertun kasalligi",
    description: "",
    image: require("./assets/Qarag‘ayning_vertun_kasalligi.jpg"),
    },
    {
    id: 34,
    title: "Barg va shoxlarning yuqumsiz kasalliklari",
    description: "",
    image: require("./assets/Barg_va_shoxlarning_yuqumsiz_kasalliklari.jpg"),
    },
    {
    id: 35,
    title: "Kuzgi tunlam",
    description: "Agrotis segetum Siff.",
    image: require("./assets/Agrotis_segetum_Siff.jpg"),
    },
    {
    id: 36,
    title: "Simqurtlar",
    description: "Elateridae",
    image: require("./assets/Elateridae.jpg"),
    },
    {
    id: 37,
    title: "Quyruqli buzoqbosh",
    description: "Gryllotolpa unispina Sauss.",
    image: require("./assets/GryllotolpaunispinaSauss.jpg"),
    },
    {
      id: 38,
      title: "Buzoqbosh qo‘ng‘izlari",
      description: "Melolonthinae",
      image: require("./assets/Melolonthinae.jpg"),
      },
      {
      id: 39,
      title: "Kaliforniya qalqondori",
      description: "Diaspidiotus Perniciosus Comst.",
      image: require("./assets/Diaspidiotus_Perniciosus_Comst.jpg"),
      },
      {
      id: 40,
      title: "Vergulsimon qalqondor",
      description: "Lepidosaphes uimi L.",
      image: require("./assets/Lepidosaphes_ulmi_L.jpg"),
      },
      {
      id: 41,
      title: "Komstok qurti",
      description: "Pseudococcus comstocki Kuw",
      image: require("./assets/Pseudococcus_comstocki_Kuw.jpg"),
      },
      {
      id: 42,
      title: "Terak bargxo‘ri",
      description: "Melasoma populi L.",
      image: require("./assets/Melasoma_populi_L.jpg"),
      },
      {
      id: 43,
      title: "Tol bargxo‘ri",
      description: "Plagiodera versicolor Laich.",
      image: require("./assets/Plagiodera_versicolor_Laich.jpg"),
      },
      {
      id: 44,
      title: "Qayrag‘och bargxo‘ri",
      description: "Galerucella luteola Muell.",
      image: require("./assets/Galerucella_luteola_Muell.jpg"),
      },
      {
      id: 45,
      title: "Tut odimchisi",
      description: "Apocheima cinerarus Efsch.",
      image: require("./assets/Apocheima_cinerarus_Efsch.jpg"),
      },
      {
      id: 46,
      title: "Toq ipak qurti",
      description: "Ocneria dispar L.",
      image: require("./assets/Ocneria_dispar_L.png"),
      },
      {
      id: 47,
      title: "Pista bargxo‘ri",
      description: "Labidostomis stenostomci Ws.",
      image: require("./assets/Labidostomis_stenostomci_Ws.jpeg"),
      },
      {
        id: 48,
        title: "Xisor pista bargxo‘ri",
        description: "Luperus hissaricus Oglob.",
        image: require("./assets/Luperus_hissaricus_Oglob.png"),
        },
        {
        id: 49,
        title: "Tol kapalagi",
        description: "Loucoma salicis L.",
        image: require("./assets/Loucoma_salicis_L.jpeg"),
        },
        {
        id: 50,
        title: "Turkiston zarkapalagi",
        description: "Euproctis Korghalica Mooro.",
        image: require("./assets/Euproctis_Korghalica_Mooro.jpg"),
        },
        {
        id: 51,
        title: "Turkiston tovusko‘zi",
        description: "Neoris stroliczkana schenki",
        image: require("./assets/Neoris_stroliczkana_schenki.jpg"),
        },
        {
        id: 52,
        title: "Amerika oq kapalagi",
        description: "Iivphantria sipea Drury.",
        image: require("./assets/Iivphantria_sipea_Drury.jpg"),
        },
        {
        id: 53,
        title: "Halqachi pilla qurt",
        description: "Malacosoma Parallela Stgr.",
        image: require("./assets/Malacosoma_Parallela_Stgr.jpg"),
        },
        {
        id: 54,
        title: "Do‘lana kapalagi",
        description: "Aporia crataegi L.",
        image: require("./assets/Aporia_crataegi_L.jpg"),
        },
        {
        id: 55,
        title: "Shahar mo‘ylovdori",
        description: "Aeolesthes sarta Solsk.",
        image: require("./assets/Aeolesthes_sarta_Solsky.jpg"),
        },
        {
        id: 56,
        title: "Katta terak oynachisi",
        description: "Aegeria apiformis.",
        image: require("./assets/Aegeria_apiformis.jpg"),
        },
        {
        id: 57,
        title: "Kichik terak oynachisi",
        description: "Paranthrene tabanifonnis.",
        image: require("./assets/Paranthrene_tabaniformis.jpg"),
        },
        {
        id: 58,
        title: "Yog‘ochxo‘r kapalak",
        description: "Zeuzera pyrina L.",
        image: require("./assets/Zeuzera_pyrina_L.jpg"),
        },
        {
        id: 59,
        title: "Terak kichik tilla qo‘ng‘izi",
        description: "Melanophila picta Pall.",
        image: require("./assets/Melanophila_picta_Pall.jpg"),
        },
        {
        id: 60,
        title: "Tyan-shan shox mo‘ylovdori",
        description: "Paururus juvencus, Paururus tianshanicus Sem.",
        image: require("./assets/Paururus_juvencus.jpg"),
        },
        {
          id: 61,
          title: "Po‘stloq osti qo‘ng‘izlari",
          description: "Scolytus rugulosus Ipidae.",
          image: require("./assets/Scolytus_rugulosus_Ipidae.jpg"),
          },
          {
          id: 62,
          title: "Qayrag‘och katta po‘stloqxo‘ri",
          description: "Scolytus scolytus",
          image: require("./assets/Scolytus_scolytus_Fabr.jpg"),
          },
          {
          id: 63,
          title: "Pista po‘stloqxo‘ri",
          description: "Chectoptelius vestitus Rey.",
          image: require("./assets/Chectoptelius_vestitus_Rey.jpg"),
          },
          {
          id: 64,
          title: "Pista urug‘xo‘ri",
          description: "Eurytoma plotairovi Nik.",
          image: require("./assets/Eurytoma_plotairovi_Nik.png"),
          },
          {
          id: 65,
          title: "Mevalar va urug‘larda qayd etilgan kasalliklar",
          description: "",
          image: require("./assets/Mevalar_va_urug‘larda_qayd_etilgan_kasalliklar.jpg"),
          },
          {
          id: 66,
          title: "Ko‘chat va nihollarda qayd etilgan kasalliklar",
          description: "",
          image: require("./assets/Ko‘chat_va_nihollarda_qayd_etilgan_kasalliklar.png"),
          },
          {
          id: 67,
          title: "Daraxtlarning barglarida qayd etilgan kasalliklar",
          description: "",
          image: require("./assets/Daraxtlarning_barglarida_qayd_etilgan_kasalliklar.jpg"),
          },
          {
          id: 68,
          title: "Daraxtlarning poyalari, novda va shoxlarini kasalliklari",
          description: "",
          image: require("./assets/Daraxtlarning_poyalari_novda_va_shoxlarini_kasalliklari.jpg"),
          },
          {
          id: 69,
          title: "Daraxtlarning poya va ildiz chirish kasalliklari",
          description: "",
          image: require("./assets/Daraxtlarning_poya_va_ildiz_chirish_kasalliklari.jpg"),
          },
          {
          id: 70,
          title: "Keng yaproqli manzarali daraxt va butalar hamda gullar kasalliklari",
          description: "",
          image: require("./assets/Manzarali_daraxt_va_butalar_hamda_gullar_kasalliklari.jpg"),
          },
          {
            id: 71,
            title: "Yong‘oq daraxti kasalliklariga qarshi kurash",
            description: "",
            image: require("./assets/Yong‘oq_daraxti_kasalliklariga_qarshi_kurash.jpg"),
          },
          {
            id: 72,
            title: "Kalmaraz kasalliklari",
            description: "",
            image: require("./assets/Id72.jpg"),
          },
          {
            id: 73,
            title: "Qora rak va sitosporoz qurish kasalliklari.",
            description: "",
            image: require("./assets/Qora_rak_va_sitosporoz_qurish_kasalliklari.jpg"),
          },
          {
            id: 74,
            title: "Bodom kasalliklari",
            description: "",
            image: require("./assets/Bodom_kasalliklari.jpg"),
          },
          {
            id: 75,
            title: "Un-shudringga",
            description: "",
            image: require("./assets/Id75.jpg"),
          },
          {
            id: 76,
            title: "Ildiz  bo‘g‘zining bakterial rak kasalligi.",
            description: "",
            image: require("./assets/Ildiz.jpg"),
          },
          {
            id: 77,
            title: "Mevalar  shishishi («karmashki») kasalligi.",
            description: "",
            image: require("./assets/77.jpg"),
          },
          {
            id: 78,
            title: "Zang  kasalliklari",
            description: "",
            image: require("./assets/Id78.jpg"),
          },
          {
            id: 79,
            title: "Igna bargli daraxtlarni zararli organizmlariga qarshi qo‘llash uchun tavsiya qilinadigan insektitsidlar, mikrobiopreparatlar va fungitsidlar ro‘yxati",
            description: "",
            image: require("./assets/79.jpg"),
          },
          {
            id: 80,
            title: "O‘rmon, keng yaproqli manzarali va mevali daraxtlar zaarkunandalariga qarshi ishlatish uchun tavsiya qilinadigan insektitsidlar, mikrobiopreparatlar ro‘yxati",
            description: "",
            image: require("./assets/Id78.jpg"),
          },
          {
            id: 100,
            title: "",
            description: "",
            image: require("./assets/Id1.jpg"),
          },
          {
            id: 101,
            title: "Igna bargli daraxtlarning zararkunandalari",
            description: "",
            image: require("./assets/Id101.jpg"),
          },
          {
            id: 102,
            title: "Igna bargi daraxtlarning asosiy kasalliklari",
            description: "",
            image: require("./assets/Id102.jpg"),
          },
          {
            id: 103,
            title: "Keng yaproqli manzarali daraxtlarning zararkunandalari",
            description: "",
            image: require("./assets/Id103.jpg"),
          },
          {
            id: 104,
            title: "Keng yaproqli manzarali daraxtlarning asosiy kasalliklari",
            description: "",
            image: require("./assets/Id104.jpg"),
          },
          {
            id: 105,
            title: "Pestitsidlar ro‘yxati",
            description: "",
            image: require("./assets/Id105.jpg"),
          },
          {
            id: 106,
            title: "Galereya",
            description: "",
            image: require("./assets/Id119.jpg"),
          },
          {
            id: 107,
            title: "Dastur haqida",
            description: "",
            image: require("./assets/Id107.jpg"),
          },
          {
            id: 108,
            title: "Ildiz, nihol va ko‘chat zararkunandalari",
            description: "",
            image: require("./assets/Id108_1.jpg"),
          },
          {
            id: 109,
            title: "Igna bargli daraxtlar so‘ruvchi zararkunandalari",
            description: "",
            image: require("./assets/Id109.jpg"),
          },
          {
            id: 110,
            title: "Igna bargli daraxtlarning bargxo‘r zararkunandalari",
            description: "",
            image: require("./assets/Id110.jpg"),
          },
          {
            id: 111,
            title: "Igna bargli daraxtlarning tana zararkunandalari",
            description: "",
            image: require("./assets/Id111.jpg"),
          },
          {
            id: 112,
            title: "Urug‘  va meva zararkunandalari",
            description: "",
            image: require("./assets/Id112.jpeg"),
          },
          {
            id: 113,
            title: "Ildiz, nihol va ko‘chat zararkunandalari",
            description: "",
            image: require("./assets/Id113_1.jpg"),
          },
          {
            id: 114,
            title: "Keng yaproqli manzarali daraxtlarning bargxo‘r zararkunandalari",
            description: "",
            image: require("./assets/Id114.jpg"),
          },
          {
            id: 115,
            title: "Keng yaproqli manzarali daraxtlarning tana zararkunandalari",
            description: "",
            image: require("./assets/Id115.jpg"),
          },
          {
            id: 116,
            title: "Urug‘ va meva zararkunandalari",
            description: "",
            image: require("./assets/Id116.jpg"),
          },
          {
            id: 117,
            title: "O‘rmon fondi o‘simliklari kasalliklari ro‘yhati",
            description: "",
            image: require("./assets/Id1.jpg"),
          },
          {
            id: 118,
            title: "Kasalliklarga qarshi kurash usullari",
            description: "",
            image: require("./assets/Id118.jpeg"),
          },
      
          {
            id: 120,
            title: "",
            description: "",
            image: require("./assets/Id1.jpg"),
          },
          
];
export default data;
